version: "3.7"

services:

  overworld-db:
      container_name: overworld-db
      image: postgres:14-alpine
      restart: always
      expose:
        - "5432"
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres

  overworld-backend:
    container_name: overworld-backend
    build: .
    restart: always
    expose:
      - "80"
    depends_on:
      - overworld-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_URL=postgresql://overworld-db:5432/postgres

  overworld:
    container_name: overworld
    image: ghcr.io/gamify-it/overworld:main
    restart: always
    expose:
      - "80"

  overworld-reverse-proxy:
    container_name: overworld-reverse-proxy
    image: nginx
    restart: always
    volumes:
      - ./.nginx/compose/nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8000:8000"