name: CloneTest
on:
  push:
    branches:
      - "**"
jobs:
  build:
    name: CloneTest
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Run clone tests
        run: mvn clean test -Dtest"CloneTest,CloneTestWithoutBackends"
        shell: bash