name: Test
on:
  push:
    branches:
      - "**"
jobs:
  build:
    name: Test
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set database url
        run: sed -i 's~spring.datasource.url=jdbc:.*~spring.datasource.url=jdbc:postgresql://host.docker.internal:5432/postgres~' src/main/resources/application.properties
        shell: bash
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Run tests
        run: mvn test

