name: Test
on:
  push:
    branches:
      - "**"
jobs:
  build:
    name: Test
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Run tests
        run: mvn test

